plugins { id "net.fabricmc.fabric-loom" }

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    implementation "net.fabricmc:fabric-loader:${project.loader_version}"
    implementation project(":core")
}

tasks.withType(JavaCompile).configureEach { options.release = 25 }

java {
    sourceCompatibility = JavaVersion.VERSION_25
    targetCompatibility = JavaVersion.VERSION_25
}

jar {
    manifest {
        attributes("Mini-Addon-Class": "com.vayolin.moreefficient.MoreEfficient")
    }
}
